# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: mikhail.mikhasenko@cern.ch
AuthorName: Mikhail Mikhasenko
Indentation: 4
JuliaMinVersion: "1.6"
License: MIT
PackageName: HadronicLineshapes
PackageOwner: mmikhasenko
PackageUUID: 49c9d978-1f9d-4e96-a984-0a9783c0b9bf
_commit: v0.9.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
